package com.fintech.backtester.model;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Represents a trading signal generated by a strategy.
 */
public record TradeSignal(LocalDate date, TradeAction action, BigDecimal price) {
}
